export const ACTION_TYPES = {
    INCREASE_WATER: "INCREASE_WATER",
    DECREASE_WATER: "DECREASE_WATER",
    INCREASE_OXYGEN: "INCREASE_OXYGEN",
    DECREASE_OXYGEN: "DECREASE_OXYGEN",
    INCREASE_TEMPLIMIT: "INCREASE_TEMPLIMIT",
    DECREASE_TEMPLIMIT: "DECREASE_TEMPLIMIT",
    WEAR_SUIT: "WEAR_SUIT",
    INSTALL_FIELD: "INSTALL_FIELD",
    CHANGE_INPUT: "CHANGE_INPUT",
}